development:
  dialect: postgres
  database: gotube_development
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5
  ssl_mode: disable

test:
  dialect: postgres
  database: gotube_test
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5
  ssl_mode: disable

production:
  dialect: postgres
  database: gotube_production
  user: postgres
  password: mysecretpassword
  host: 127.0.0.1
  pool: 5
  ssl_mode: disable
